site_name: Infernet ML
site_description: Infernet ML Documentation

nav:
  - Quickstart: quickstart.md
  - Architecture: architecture.md
  - Managing Artifacts: artifacts.md
  - EZKL Artifacts: ezkl_artifacts.md
  - Managing Models: models.md
  - Working With Vectors: vectors.md
