site_name: Infernet ML
site_description: Infernet ML Documentation

nav:
  - Quickstart: quickstart.md
  - Architecture: architecture.md
  - Model Upload & Download: models.md
  - Working With Vectors: vectors.md
  - Managing Artifacts: artifacts.md
  - EZKL: ezkl_artifacts.md
