name: Run Infernet Service Tests

on:
  pull_request:
  repository_dispatch:
    types: [run-e2e-node-tests-event]
  workflow_dispatch:
    inputs:
      docker-tag:
        description: 'Infernet Node Docker tag'
        required: true
        type: string
        default: 'latest'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
