name: Run Infernet Service Tests

on:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: 'Infernet Node Docker tag'
        required: true
        type: string
        default: 'latest'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
