name: Run Infernet Service Tests

on:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: 'Infernet Node Docker tag'
        required: true
        type: string
        default: 'latest'